# Generated by Django 4.2.6 on 2024-03-20 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20)),
                ('make', models.CharField(max_length=100)),
                ('colour', models.CharField(max_length=50)),
                ('year_of_manufacture', models.IntegerField()),
                ('fuel_type', models.CharField(max_length=50)),
                ('tax_status', models.CharField(max_length=50)),
                ('tax_due_date', models.DateField()),
                ('mot_status', models.CharField(max_length=50)),
                ('mot_expiry_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
