# Generated by Django 4.2.6 on 2024-03-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='engine_capacity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
