# Generated by Django 4.2.6 on 2024-03-29 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_vehicle_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='user',
            new_name='user_id',
        ),
    ]
