# Generated by Django 4.2.6 on 2024-03-30 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_vehiclelog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiclelog',
            old_name='vehicle_id',
            new_name='registration_number',
        ),
    ]
