# Generated by Django 4.2.6 on 2024-03-30 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_vehicle_id_vehiclelog_registration_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiclelog',
            old_name='registration_number',
            new_name='vehicle_id',
        ),
        migrations.RemoveField(
            model_name='vehiclelog',
            name='user_id',
        ),
    ]
