# Generated by Django 4.2.6 on 2024-04-03 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_comment_reply_post_comment_post_id_comment_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='description',
        ),
    ]
