# Generated by Django 4.2.6 on 2024-04-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_comment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=5000),
        ),
    ]
