# Generated by Django 4.2.6 on 2024-04-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_comment_comment_alter_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='tax_due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
